package models

const (
	ProviderCopilot ModelProvider = "copilot"
)

var CopilotModels = map[ModelID]Model{
	"copilot.gpt-4.1": {
		ID:                  "copilot.gpt-4.1",
		Name:                "GPT-4.1 (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "gpt-4.1",
		CostPer1MIn:         0.0, // GitHub Copilot subscription covers costs
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       128000,
		DefaultMaxTokens:    4096,
		CanReason:           true,
		SupportsAttachments: true,
	},
	"copilot.gpt-4o": {
		ID:                  "copilot.gpt-4o",
		Name:                "GPT-4o (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "gpt-4o",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       128000,
		DefaultMaxTokens:    4096,
		CanReason:           true,
		SupportsAttachments: true,
	},
	"copilot.gpt-4o-mini": {
		ID:                  "copilot.gpt-4o-mini",
		Name:                "GPT-4o Mini (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "gpt-4o-mini",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       128000,
		DefaultMaxTokens:    4096,
		CanReason:           false,
		SupportsAttachments: true,
	},
	"copilot.claude-3.7-sonnet": {
		ID:                  "copilot.claude-3.7-sonnet",
		Name:                "Claude 3.7 Sonnet (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "claude-3.7-sonnet",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    8192,
		CanReason:           true,
		SupportsAttachments: true,
	},
	"copilot.claude-3.5-sonnet": {
		ID:                  "copilot.claude-3.5-sonnet",
		Name:                "Claude 3.5 Sonnet (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "claude-3.5-sonnet",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    8192,
		CanReason:           true,
		SupportsAttachments: true,
	},
	"copilot.claude-3.5-haiku": {
		ID:                  "copilot.claude-3.5-haiku",
		Name:                "Claude 3.5 Haiku (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "claude-3.5-haiku",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    8192,
		CanReason:           false,
		SupportsAttachments: true,
	},
	"copilot.claude-4-sonnet": {
		ID:                  "copilot.claude-4-sonnet",
		Name:                "Claude 4 Sonnet (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "claude-sonnet-4",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       200000,
		DefaultMaxTokens:    8192,
		CanReason:           true,
		SupportsAttachments: true,
	},
	"copilot.gemini-2.5-flash": {
		ID:                  "copilot.gemini-2.5-flash",
		Name:                "Gemini 2.5 Flash (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "gemini-2.5-flash",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       1048576,
		DefaultMaxTokens:    8192,
		CanReason:           true,
		SupportsAttachments: true,
	},
	"copilot.o1-preview": {
		ID:                  "copilot.o1-preview",
		Name:                "o1-preview (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "o1-preview",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       128000,
		DefaultMaxTokens:    32768,
		CanReason:           true,
		SupportsAttachments: false,
	},
	"copilot.o1-mini": {
		ID:                  "copilot.o1-mini",
		Name:                "o1-mini (Copilot)",
		Provider:            ProviderCopilot,
		APIModel:            "o1-mini",
		CostPer1MIn:         0.0,
		CostPer1MOut:        0.0,
		CostPer1MInCached:   0.0,
		CostPer1MOutCached:  0.0,
		ContextWindow:       128000,
		DefaultMaxTokens:    65536,
		CanReason:           true,
		SupportsAttachments: false,
	},
}
